# Generated by Django 4.1.7 on 2024-01-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
