# Generated by Django 4.1.7 on 2024-01-03 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Flatapp', '0002_owner_active_registration_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='elect_img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('furnish', models.CharField(blank=True, max_length=200, null=True)),
                ('atype', models.CharField(blank=True, max_length=200, null=True)),
                ('ebill', models.CharField(blank=True, max_length=200, null=True)),
                ('extra', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('rent', models.CharField(blank=True, max_length=200, null=True)),
                ('pic1', models.FileField(blank=True, null=True, upload_to='')),
                ('pic2', models.FileField(blank=True, null=True, upload_to='')),
                ('pic3', models.FileField(blank=True, null=True, upload_to='')),
                ('pic4', models.FileField(blank=True, null=True, upload_to='')),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Flatapp.owner')),
            ],
        ),
    ]
