# Generated by Django 4.1.7 on 2024-01-10 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Flatapp', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardno', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, default='Booking Amount', max_length=100, null=True)),
                ('nameoncard', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, default='Booked', max_length=100, null=True)),
                ('bookingdate', models.DateTimeField(auto_now_add=True)),
                ('apart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Flatapp.apartment')),
                ('register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Flatapp.registration')),
            ],
        ),
    ]
