# Generated by Django 4.1.7 on 2024-01-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flatapp', '0005_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='active',
        ),
        migrations.AddField(
            model_name='apartment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Disapproved')], default=1),
        ),
    ]
