# Generated by Django 4.1.7 on 2024-01-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flatapp', '0006_remove_apartment_active_apartment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Deactivate')], default=1),
        ),
    ]
