# Generated by Django 4.1.7 on 2024-01-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flatapp', '0007_alter_apartment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='active',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='active',
        ),
        migrations.AddField(
            model_name='owner',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=2),
        ),
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
    ]
